### PR TITLE
writeValueWithoutResponse support implemented

### PR DESCRIPTION
**Pull request by steffenmauch**
This patch adds the writeValueWithoutResponse support for WebBLE

### CODE REVIEW

**Comment by daphtdazz** [comment]
Hey @steffenmauch , thanks for this, have you got a device you've been testing with? If so would you be able to add a folder for it in DeviceTests, like the existing Puck.js test, and add a test case for it? I want to try and avoid adding code without tests now, and it is going to be valuable to start accumulating a library of tests for different devices. I will try and review the code at the weekend.

**Comment by steffenmauch** [comment]
Hey, I do have a device but until now, that device is not published. Is this a criteria for adding it?

**Comment by steffenmauch** [comment]
Hey @daphtdazz, do you see any change to merge this or do I have to provide you a device where you can test with?

**Comment by daphtdazz** [comment]
Closing since I have now implemented this and `writeValueWithResponse` in [59](https://github.com/daphtdazz/WebBLE/pull/59) (and this is now released as version 1.7.0 of WebBLE on the app store).

**Pull request closed without merging**
